#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 12) Escreva um algoritmo para ler as dimensões de um trapézio
# (base amior, base menor e altura), calcular e escrever a área do trapézio. a=(B+b).h/2

base_maior=float(input("Digite a base maior do trapézio: "))
base_menor=float(input("Digite a base menor do trapézio: "))
altura=float(input("Digite a altura do trapézio: "))
area=((base_maior+base_menor)*altura)/2
print("A área do trapézio é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")