#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 13) Escreva um algoritmo para ler as dimensões 
# de um circulo (raio), calcular e escrever a área do circulo. a=pi*r²

pi=3.141592653589793
raio=float(input("Digite o raio do círculo: "))
area=pi*(raio**2)
print("A área do círculo é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")