#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 11) Escreva um algoritmo para ler as dimensões de um losango 
# (diagonal maior, diagonal menor), calcular e escrever a área do losango. Dica a=D.d/2

diagonal_maior=float(input("Digite a diagonal maior do losango: "))
diagonal_menor=float(input("Digite a diagonal menor do losango: "))
area=(diagonal_maior*diagonal_menor)/2
print("A área do losango é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")