#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 9) Escreva um algoritmo para ler as dimensões de um triângulo (base e altura),
# calcular e escrever a área do triângulo. Dica a=b.h/2

base=float(input("Digite a base do triângulo: "))
altura=float(input("Digite a altura do triângulo: "))
area=(base*altura)/2
print("A área do triângulo é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")