#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 8) Escreva um algoritmo para ler as dimensões de 
# um retângulo (base e altura), calcular e escrever a área do retângulo. Dica a=b.h

base=float(input("Digite a base do retângulo: "))
altura=float(input("Digite a altura do retângulo: "))
area=base*altura
print("A área do retângulo é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")