#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 10) Escreva um algoritmo para ler as dimensões de um quadrado (lado),
# calcular e escrever a área do quadrado. Dica a=l²

lado=float(input("Digite o lado do quadrado: "))
area=lado**2
print("A área do quadrado é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")