#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 4) Escreva um algoritmo para ler dois valores
# do teclado e exibir como resposta a divisão dos valores.
# Leitura dos valores do teclado

valor1=float(input("Digite o primeiro valor: "))
valor2=float(input("Digite o segundo valor: "))
divisao=valor1/valor2
print("A divisão do primeiro valor pelo segundo é:", divisao)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")