#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 1) Escreva um algoritmo para ler dois valores do 
# teclado e exibir como resposta a soma dos valores.


valor1=float(input("Digite o primeiro valor: "))
valor2=float(input("Digite o segundo valor: "))
soma=valor1+valor2
print("A soma dos valores é:", soma)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")