#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 5) Escreva um algoritmo para ler dois valores do 
# teclado (base e exponenciação) e exibir como resposta a exponenciação.

base=float(input("Digite a base: "))
expoente=float(input("Digite o expoente: "))
resultado=base**expoente
print("O resultado de", base, "elevado a", expoente, "é:", resultado)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")