#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 6) Escreva um algoritmo para ler um valor do 
# teclado e exibir como resposta o número sucessor

valor=int(input("Digite um valor: "))
sucessor=valor+1
print("O antecessor do valor", valor, "é:", sucessor)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")