#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 14) Escreva um algoritmo para ler as dimensões de
# um hexagono, calcular e escrever a área do hexagono.

sqrt_3=1.7320508075688772
lado=float(input("Digite o lado do hexágono: "))
area=(3*sqrt_3/2)*(lado**2)
print("A área do hexágono é:", area)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")